[project]
name = "cli-o"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.12"
dependencies = []
=======
requires-python = ">=3.10"
dependencies = [
    "nemo>=7.1.4",
    "scipy>=1.15.2",
    "sounddevice>=0.5.1",
    "torch>=2.7.0",
]
>>>>>>> 20c0c0b (voice to wav file working)
