questions = [
    # Web search questions
    "What’s the weather like today in San Francisco?",
    "Who won the Super Bowl this year?",
    "Where can I buy a used graphics card online?",
    "When is the next solar eclipse?",
    "What’s a good sushi restaurant nearby?",
    "How do I renew a passport?",
    "What’s the cheapest flight from Los Angeles this weekend?",
    "What are today’s top news stories?",
    "Who’s performing at Coachella this year?",
    "Where can I watch the latest Marvel movie?",
    "What are common flu symptoms?",
    "What’s the average rent in Seattle?",
    "When does school start in New York?",
    "What are the side effects of ibuprofen?",
    "Who is the richest person right now?",
    "What’s trending online right now?",
    "How tall is Mount Everest?",
    "When does the next iPhone come out?",
    "Where can I donate clothes nearby?",
    "What’s a cheap summer travel destination?",

    # Wikipedia summary questions
    "Who is Nikola Tesla?",
    "What is general relativity?",
    "What was the French Revolution?",
    "What was the Great Depression?",
    "What does HTTP stand for?",
    "What is democracy?",
    "What is photosynthesis?",
    "What is evolution?",
    "Who was Cleopatra?",
    "What is machine learning?",
    "What happened during the moon landing?",
    "What is the Big Bang theory?",
    "Who invented the telephone?",
    "What is the Statue of Liberty?",
    "What does the heart do?",
    "What is quantum mechanics?",
    "How did the internet start?",
    "Who were the samurai?",
    "What are black holes?",
    "What was the Roman Empire?",

    # Python interpreter questions
    "What is 30 times 12?",
    "What is 8 factorial?",
    "Give 5 random numbers between 10 and 100.",
    "Convert 32 Celsius to Fahrenheit.",
    "Sum the numbers from 1 to 100.",
    "Is 101 a prime number?",
    "What’s the area of a triangle with base 10 and height 5?",
    "List the first 6 powers of 2.",
    "What is 3 squared plus 4 squared?",
    "Sort the numbers 5, 3, 9, 1, and 6.",
    "How many days are in 7 years?",
    "List even numbers between 1 and 20.",
    "What’s the standard deviation of [2, 4, 4, 4, 5, 5, 7, 9]?",
    "Create a dictionary with names and ages.",
    "What is the cube root of 64?",
    "What is pi to 10 decimal places?",
    "What’s today’s date and time using Python?",
    "Reverse the string 'hello world'.",
    "What is 2.5 to the power of 4?",
    "Give me a list of squares from 1 to 10.",

    # Linux shell tool questions (textual outputs only)
    "What command shows files in the current folder?",
    "How do I check the current working directory?",
    "How do I check available disk space?",
    "What command lists all .txt files in a directory?",
    "How do I display the first 10 lines of a file?",
    "How can I search for the word 'error' in a log file?",
    "What command shows today’s date and time?",
    "How do I list all running processes?",
    "What command shows hidden files in a folder?",
    "How do I find the number of lines in a file?",
    "What’s the command to download a file from a URL?",
    "What’s the command to change directories?",
    "How do I see the current logged-in user?",
    "What command shows the content of a text file?",
    "How do I display memory usage on Linux?",
    "What does the 'ls -l' command show?",
    "How do I count the number of words in a file?",
    "What command shows system uptime?",
    "What’s the command to search for files by name?",
    "How do I check the system hostname?",

    # Geometry Dash RL repo questions
    "How do I train the Geometry Dash AI?",
    "What reward does the model use?",
    "Can I set a custom checkpoint?",
    "Does the AI handle gravity changes?",
    "What’s the average reward per episode?",
    "Where is training progress saved?",
    "How do I turn on frame step mode?",
    "How do I send a jump command?",
    "Can you list saved safe states?",
    "How do I restart the level?",
    "How often are frames sent to the model?",
    "How can I see the agent’s run?",
    "What’s the last checkpoint reached?",
    "Can I see the last frame buffer?",
    "Is the model overfitting to the start?",
    "How many frames were used last episode?",
    "How do I test the model on a new level?",
    "Can I control jump duration?",
    "What’s the state format for jump actions?",
    "How do I load a saved model checkpoint?"
]
